### ISSUE TITLE
start fragments on navigation drawer onclick

### ISSUE THREAD

**Issue by rajvijay68** [NITT-SHG/Seller#1]
@ajish-sekar  , can you see why the `onNavigationItemSelected` isn't being called on clicking menu items in `HomeActivity.java`?

What we want is the corresponding fragment to come up when clicked.

**Comment by ajish-sekar** [comment]
You cannot use `onNavigationItemSelected` with navigation controller, either remove that or use navigation graphs
[Navigation Guide](https://developer.android.com/guide/navigation/navigation-getting-started)

or for a hacky way use this
`
navController.addOnDestinationChangedListener(new NavController.OnDestinationChangedListener() {
            @Override
            public void onDestinationChanged(@NonNull NavController controller, @NonNull NavDestination destination, @Nullable Bundle arguments) {
                switch (destination.getId()){
                    // Do whatever is required
                }
            }
        });
`
